eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: server-zuul

#\u8DEF\u7531zuul\u914D\u7F6E
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: server-ribbon
    api-b:
      path: /api-b/**
      serviceId: server-feign